name: Sprint
main: com.Carbon131.Sprint.Sprint
version: 1.31z
author: Zarius
authors: [Zarius,Carbon131]
# small modifications by Zarius (March 2012) for BukkitR5+ compatibility
# & now taken over development (June 2013)
softdepend:
  - AntiCheat
commands:
  sprint:
    description: Modify sprint configuration settings.
    usage: /<command>
